class Strings {
  static const String appName = "Beta24";

  static const String createAccount = 'Create Account';
  static const String uploadProfilePhoto = 'Upload Profile Photo';
  static const String yourFullName = 'Your Full Name';
  static const String birthdayDateHint = 'YYYY-MM-DD';
  static const String emailAddress = 'Email Address';
  static const String serviceType = 'Service Type';
  static const String selectGender = 'Select Gender';
  static const String referralCode = 'Referral Code';
  static const String accountType = 'Account Type';
  static const String enterYourReferralCode = 'Enter Your Referral Code';
  static const String next = 'Next';
  static const String submit = 'Submit';
  static const String done = 'Done';
  static const String update = 'Update';
  static const String version = 'Version';
  static const String welcomeTo = 'Welcome To';
  static const String getOTP = 'Get OTP';
  static const String mobileNumber = 'Mobile Number';
  static const String verify = 'Verify';
  static const String verificationCode = 'Verification Code';
  static const String weSentVerificationCodeOnYourNumber = 'We sent the verification code on your number';
  static const String didNotReceiveCode = 'Didn’t Receive Code?';
  static const String resend = 'Resend';
  static const String home = 'Home';
  static const String offers = 'Offers';
  static const String notification = 'Notification';
  static const String booking = 'Booking';
  static const String profile = 'Profile';
  static const String myProfile = 'My Profile';
  static const String editProfile = 'Edit Profile';
  static const String edit = 'Edit';
  static const String logout = 'Logout';
  static const String delete = 'Delete';
  static const String cancel = 'Cancel';
  static const String reject = 'Reject';
  static const String report = 'Report';
  static const String pay = 'Pay';
  static const String areYouSureYouWantLogoutYourAccount = 'Are you sure you want to logout your account?';
  static const String areYouSureYouWantDeleteYourAccount = 'Are you sure you want to delete your account?';
  static const String wallet = 'Wallet';
  static const String myDocument = 'My Document';
  static const String complaints = 'Complaints';
  static const String referral = 'Referral';
  static const String becomeRider = 'Become a Rider';
  static const String settings = 'Settings';
  static const String howToUse = 'How to Use';
  static const String aboutUs = 'About Us';
  static const String privacyPolicy = 'Privacy Policy';
  static const String termsConditions = 'Terms & Conditions';
  static const String helpSupport = 'Help & Support';
  static const String unauthorisedUser = 'Unauthorised User';
  static const String agreeToThe = 'I agree to the';
  static const String uploadProfilePicture = 'Upload Profile Picture';
  static const String noInternetConnectionPleaseTryAgain = 'No internet connection. Please try again.';
  static const String failedToCheckInternetConnectionPleaseTryAgain = 'Failed to check internet connection. Please try again.';
  static const String currentLocation = 'Current Location';
  static const String beta = 'Beta';
  static const String beti = 'Beti';
  static const String createTask = 'Create Task';
  static const String or = 'Or';
  static const String signInWithGoogle = 'Sign in with google';
  static const String deleteAccount = 'Delete Account';
  static const String transactions = 'Transactions';
  static const String addMoney = 'Add Money';
  static const String walletBalance = 'Wallet Balance';
  static const String enterAmount = 'Enter Amount';
  static const String active = 'Active';
  static const String welcomeToYourBeta24App = 'Welcome to Your Beta24 App';
  static const String chooseYourBeta24BookingEasily = 'Choose Your Beta24 Booking Easily';
  static const String bookTaskAnytimeAnywhere = 'Book a Task Anytime, Anywhere!';
  static const String getStarted = 'Get Started';
  static const String enableLocationService = 'Enable Location Service';
  static const String enableLocationPermission = 'Enable Location Permission';
  static const String enableLocationServicesYourDeviceInside = 'Enable location services on your device inside';
  static const String privacy = 'Privacy';
  static const String locationServices = 'location services';
  static const String okGotIt = 'Ok, got it';
  static const String openSetting = 'Open Setting';
  static const String locationPermissionDescription = 'Enable location permission to fetch your current location';
  static const String searchPlace = 'Search place';
  static const String ourTeamWillBeContactYouWithin24 = 'Our team will be contact\nyou within 24 hrs.';
  static const String setting = 'Setting';
  static const String yourReferralCode = 'Your referral code:';
  static const String copy = 'Copy';
  static const String shareYourReferralCodeWithYourFriends = 'Share your referral code with your\nfriends and get benefits.';
  static const String inviteFriends = 'Invite Friends';
  static const String noDataFound = 'No Data Found';
  static const String user = 'User';
  static const String rider = 'Rider';
  static const String title = 'Title';
  static const String description = 'Description';
  static const String callUs = 'Call Us';
  static const String bookingDetails = 'Booking Details';
  static const String approve = 'Approve';
  static const String taskDetails = 'Task Details';
  static const String viewOnMap = 'view on map';
  static const String estimationDetails = 'Estimation Details';
  static const String paymentDetails = 'Payment Details';
  static const String paymentRequired = 'Payment Required';
  static const String estimatedDistance = 'Estimated Distance';
  static const String estimatedTime = 'Estimated Time';
  static const String estimatedAmount = 'Estimated Amount';
  static const String totalAmount = 'Total Amount';
  static const String payableAmount = 'Payable Amount';
  static const String walletAmount = 'Wallet Amount';
  static const String discount = 'Discount';
  static const String areYouSureYouWantMarkThisTaskAsDone = 'Are you sure you want to mark this\ntask as done?';
  static const String yes = 'Yes';
  static const String no = 'No';
  static const String mentionHereReasonNotCancelThisTask = 'Mention here a reason for canceling this task.';
  static const String mentionHereReasonWhyYouAreRejectingThisTask = 'Mention here a reason why you are rejecting this task.';
  static const String dateTime = 'Date/Time';
  static const String bookingId = 'Booking ID';
  static const String status = 'Status';
  static const String raiseComplaint = 'Raise Complaint';
  static const String promoCode = 'Promo Code';
  static const String enterPromoCode = 'Enter promo code';
  static const String apply = 'Apply';
  static const String applyCode = 'Apply Code';
  static const String promoCodeApplied = 'Promo code Applied';
  static const String paymentSuccessful = 'Payment Successful';
  static const String withdrawal = 'Withdrawal';
  static const String photos = 'Photos';
  static const String addPhoto = 'Add Photo';
  static const String remark = 'Remark';
  static const String distance = 'Distance';
  static const String duration = 'Duration';
  static const String remove = 'Remove';
  static const String note = 'Note: ';
  static const String itAllDependsOnTheTimeTheTaskCompleted = 'It all depends on the time for the task completed.';
  static const String cancellationChargesMayApply = 'Cancellation charges may apply.';
  static const String category = 'Category';
  static const String bike = 'Bike';
  static const String walking = 'Walking';
  static const String accountPrivacy = 'Account Privacy';


  //Task Status
  static const String requestForApproval = 'Request for Approval'; //1
  static const String inTransit = 'In Transit'; //2
  static const String payment = 'Payment'; //3
  static const String completed = 'Completed'; //4
  static const String cancelled = 'Cancelled'; //5

  //Complaint Status
  static const String inProgress = 'In Progress'; //1
  static const String resolved = 'Resolved'; //2
  static const String withdraw = 'Withdraw'; //3
}
